### ISSUE TITLE
Add authentication to longhorn

### ISSUE THREAD

**Issue by Dremor** [rancher/longhorn-ui#14]
Hi

Would it be possible to add authentication to Longhorn ? A simple password would be enough, no need for a full fledged user management. 

This would allow to expose the UI on the net (for remote administration).

**Comment by yasker** [comment]
Yeah, it's in our plan. We're planning to do it after the next release.

BTW, it's OK to file all the issues in `rancher/longhorn`. It would be easy to track everything in one place. I will move this topic there.
